name: Pull-Request

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    # pull_request event is required only for autolabeler
    types: [assigned, opened, reopened, synchronize]

jobs:
  # Dependency Review Action
  #
  # This Action will scan dependency manifest files that change as part of a Pull Reqest, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
  #
  # Source repository: https://github.com/actions/dependency-review-action
  # Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3

  auto_labeler:
    needs: labeler
    name: auto-label
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.base.ref != 'main' && github.event.pull_request.head.ref != 'develop' }}
    permissions:
      contents: read
      pull-requests: write # for release-drafter/release-drafter to add label to PR
    steps:
      - name: 'Pull request auto-labeler'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  danger-js:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Danger
        run: pnpm danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
